[package]
name = "ofs-convert-rs"
version = "0.1.0"
authors = ["Lukas Behrendt <lukas.behrendt@student.hpi.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
